### ISSUE TITLE
Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by rociorius** [broadinstitute/gnomad-browser#1401] opened 2024-01-30 06:33 UTC
**Description**: clicked on Variant ID GD_16P12.2__DEL

**Error message**: Cannot read properties of null (reading 'map')

**Stack trace**:
```
TypeError: Cannot read properties of null (reading 'map')
    at Z (https://gnomad.broadinstitute.org/js/326-76f749083ae39bff05f7.js:21:7278)
    at Yi (https://gnomad.broadinstitute.org/js/bundle-ff3a5528c7d88c12b975.js:39:172114)
    at wu (https://gnomad.broadinstitute.org/js/bundle-ff3a5528c7d88c12b975.js:39:218019)
    at pl (https://gnomad.broadinstitute.org/js/bundle-ff3a5528c7d88c12b975.js:39:210795)
    at fl (https://gnomad.broadinstitute.org/js/bundle-ff3a5528c7d88c12b975.js:39:210720)
    at rl (https://gnomad.broadinstitute.org/js/bundle-ff3a5528c7d88c12b975.js:39:207750)
    at https://gnomad.broadinstitute.org/js/bundle-ff3a5528c7d88c12b975.js:39:159523
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-ff3a5528c7d88c12b975.js:39:314904)
    at Vo (https://gnomad.broadinstitute.org/js/bundle-ff3a5528c7d88c12b975.js:39:159232)
    at Ko (https://gnomad.broadinstitute.org/js/bundle-ff3a5528c7d88c12b975.js:39:159468)
```

**Route**: /variant/GD_16P12.2__DEL?dataset=gnomad_sv_r4

**Browser**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by rileyhgrant** [comment] 2024-02-01 20:41
Hello @rociorius 

We are looking into this problem per #1380.

As such, we will be closing this issue as a duplicate of #1380

**Closed by rileyhgrant** 2024-02-01 20:41 UTC
