### ISSUE TITLE
Add copy number variants (v4)

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#1118] opened 2023-06-08 19:32 UTC
For reference, what they looked like in ExAC:

![image](https://github.com/broadinstitute/gnomad-browser/assets/8867295/69114880-14d1-4af2-930a-476396bee1ba)

**Comment by sjahl** [comment] 2023-08-17 20:15
is this a duplicate of #1133 ?

**Comment by rileyhgrant** [comment] 2023-08-24 19:19
Closing as duplicate of #1133

**Closed by rileyhgrant** 2023-08-24 19:19 UTC
