### ISSUE TITLE
Render error on /variant/Y-2787008-C-T?dataset=gnomad_r3

### ISSUE THREAD

**Issue by Mahakoud** [broadinstitute/gnomad-browser#1116] opened 2023-06-03 16:11 UTC
### What you actually saw after you did that:

Any of the following information will be helpful:

* Screenshots
   How to take a screenshot on macOS: https://support.apple.com/en-us/HT201361
   How to attach an image to an issue: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

* Error messages that appear on the page or in the browser console
   How to open the console on Chrome: https://developers.google.com/web/tools/chrome-devtools/console/#opening_the_console

-->

**Comment by phildarnowsky-broad** [comment] 2023-06-05 13:12
Renders correctly with a "Variant Not Found" error when I try it. Confirmed via the API that v3 data has no variant with this ID.

**Comment by rileyhgrant** [comment] 2023-06-22 20:23
I also see a variant not found page correctly, see screenshot below.

Viewing the surrounding region and including filtered variants in the table, I do not see this variant appear. Leaving this on `Triage` to discuss briefly in Browser Meeting next week, though it is expected to be closed since we are unable to replicate this bug.

![Screenshot 2023-06-22 at 15 21 08](https://github.com/broadinstitute/gnomad-browser/assets/59549713/edea98af-1b06-40d1-b2aa-c94eee7f89a1)

**Comment by rileyhgrant** [comment] 2023-06-26 15:40
Closing this issue as we are unable to replicate.

**Closed by rileyhgrant** 2023-06-26 15:40 UTC
Labels: Triage
