### ISSUE TITLE
AttributeError: 'list' object has no attribute 'attrib'

### ISSUE THREAD

**Issue by daniaki** [broadinstitute/gnomad-browser#1046] opened 2022-11-29 05:15 UTC
We're trying to get the gnomAD data pipeline running following the guides in this repository. I'm hitting this error while running the `clinvar_grch37` data pipeline step which is parsing the [2022-11-20](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/clinvar_variation/weekly_release/ClinVarVariationRelease_2022-1120.xml.gz) Clinvar XML file:

```
Parsing XML file
  1%|          | 12476/1100000 [00:13<20:42, 875.10it/s]Failed to parse variant 151314
Traceback (most recent call last):
  File "/tmp/1176299b30c0490db29348b9b1b477a1/clinvar_grch37.py", line 80, in <module>
    run_pipeline(pipeline)
  File "/tmp/1176299b30c0490db29348b9b1b477a1/pyfiles_e3ra1vi2.zip/data_pipeline/pipeline.py", line 200, in run_pipeline
  File "/tmp/1176299b30c0490db29348b9b1b477a1/pyfiles_e3ra1vi2.zip/data_pipeline/pipeline.py", line 167, in run
  File "/tmp/1176299b30c0490db29348b9b1b477a1/pyfiles_e3ra1vi2.zip/data_pipeline/pipeline.py", line 132, in run
  File "/tmp/1176299b30c0490db29348b9b1b477a1/pyfiles_e3ra1vi2.zip/data_pipeline/datasets/clinvar.py", line 191, in import_clinvar_xml
  File "/tmp/1176299b30c0490db29348b9b1b477a1/pyfiles_e3ra1vi2.zip/data_pipeline/datasets/clinvar.py", line 115, in _parse_variant
AttributeError: 'list' object has no attribute 'attrib'
```

This is run on dataproc using the command `./deployctl data-pipeline run --cluster vep85 clinvar_grch37`. It appears to be caused by the f-string in this print statement:

```python
allele_element = variant_element.findall("./InterpretedRecord/SimpleAllele")
print(f'Skipping variant with Allele ID: {allele_element.attrib["AlleleID"]} due to anomalous Chromosome value of "Un"')
```

Seems like the `findall` method is returning a list of XML nodes when the f-string expects a single node to be present. The cluster is using python 3.8 if that helps.

**Comment by rileyhgrant** [comment] 2022-11-29 14:38
Howdy,

Looks like you're exactly right. There will be a one line PR that fixes this soon. It does exactly what you said - changes the fstring to look for the `attrib` of the first element `findall` finds (`...allele_element[0].attrib...`).

If you haven't already, and/or don't want to wait for the PR to get merged, changing the lines you called out:

```
allele_element = variant_element.findall("./InterpretedRecord/SimpleAllele")
print(f'Skipping variant with Allele ID: {allele_element.attrib["AlleleID"]} due to anomalous Chromosome value of "Un"')
```
To
```
allele_element = variant_element.findall("./InterpretedRecord/SimpleAllele")
print(f'Skipping variant with Allele ID: {allele_element[0].attrib["AlleleID"]} due to anomalous Chromosome value of "Un"')
```

Will allow the `ClinVar` pipeline to run successfully - I just confirmed that change fixes it.

Thanks for the issue, the detailed sleuthing, and the exact lines!

Riley

**Closed** 2022-11-29 17:14 UTC
