### ISSUE TITLE
Error in subpopulations (missing/duplicated) of downloaded data (v2)

### ISSUE THREAD

**Issue by michellepaczosa** [broadinstitute/gnomad-browser#1394] opened 2024-01-22 17:56 UTC
### What you did:

I downloaded the gnomAD data for the genes listed above from v2.1.1 website by going to the "export variants to csv" button
e.g., https://gnomad.broadinstitute.org/gene/ENSG00000117400?dataset=gnomad_r2_1

### What you expected to see after you did that:

<!-- I opened up the document downloaded using excel and reviewed the subpopulations for the variant. 

### What you actually saw after you did that:

<!--I expected there to be all the subpopulations listed. However, the african american subpop data was listed twice and the latino/admixed subpopulations were missing. 

<!--

Any of the following information will be helpful:

[gnomAD_v2.1.1_ENST00000372470_2024_01_22_11_42_42.csv](https://github.com/broadinstitute/gnomad-browser/files/14013728/gnomAD_v2.1.1_ENST00000372470_2024_01_22_11_42_42.csv)

[gnomAD_v2.1.1_ENST00000268206_2024_01_22_12_54_51.csv](https://github.com/broadinstitute/gnomad-browser/files/14013741/gnomAD_v2.1.1_ENST00000268206_2024_01_22_12_54_51.csv)

**Comment by rileyhgrant** [comment] 2024-01-22 20:51
Hiya @michellepaczosa, thanks for filing this issue. Could you take a look at this issue filed recently #1393 and see if that encompasses the issue? If so, I'll close this issue as a duplicate in favor the #1393. Let us know! 

Thanks

**Comment by michellepaczosa** [comment] 2024-01-22 21:12
Hi,
Thank you for reaching out. Yes, that ticket appears to be for the same
issue I created a ticket for.
Thanks,
Michelle

**Comment by rileyhgrant** [comment] 2024-01-22 22:51
Great, thanks @michellepaczosa. We'll look into fixing this, and I'll close this issue as a duplicate of #1393.

Thank you!

**Closed by rileyhgrant** 2024-01-22 22:51 UTC
