### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by SueClasper** [broadinstitute/gnomad-browser#1163] opened 2023-08-18 09:11 UTC
Stack trace:
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at hu (https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:200764)
    at vl (https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:213935)
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:314904)
    at Vo (https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:159232)
    at yl (https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:211795)
    at rl (https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:207949)
    at https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:159523
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:314904)
    at Vo (https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:159232)
    at Ko (https://gnomad.broadinstitute.org/js/bundle-a6daedabf4613e63fb59.js:39:159468)
```

Route: /variant/6-161127501-A-G?dataset=gnomad_r2_1

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by SueClasper** [comment] 2023-08-18 09:12
I can't link out to the frequency table in gnomAD

**Comment by rileyhgrant** [comment] 2023-08-24 22:20
Hiya @SueClasper! Thanks for submitting this issue

I'm not able to replicate this, can you let me know what you're doing differently?

In trying to reproduce this I:
- Went to the Variant page you linked
- Expanded every population in the "population frequencies" table
- Sorted on every column in the table
- Filtered the table to be only genomes, only exomes, and both

In trying all of these above, I cannot replicate this crash. Is the populations frequency table what you meant by the frequency table? Is there something I'm not doing that you did?

If I'm unable to replicate this issue, this issue will be closed as resolved.

**Comment by rileyhgrant** [comment] 2023-08-31 20:08
Closing because this issue cannot be replicated. 

I tried again just now to interact with all of the elements of the page that can be interacted with, and was not able to replicate this.

**Closed by rileyhgrant** 2023-08-31 20:08 UTC
