### ISSUE TITLE
Data Pipeline Genes Error

### ISSUE THREAD

**Issue by theBobiKing** [broadinstitute/gnomad-browser#1099] opened 2023-03-28 07:51 UTC
Hey everybody,

In the last few days, I've been trying to run a data pipeline with a genes argument following this documentation: https://github.com/broadinstitute/gnomad-browser/blob/main/data-pipeline/README.md

Note: Before running data pipeline, I have run ./deploy setup from here https://github.com/broadinstitute/gnomad-browser/tree/main/deploy

However, after ~14/17 minutes of running genes pipeline it fails with the following error message:

Hail version: 0.2.109-b71b065e4bb6
Error summary: MethodTooLargeException: Method too large: __C1355collect_distributed_array_table_text_writer.__m1423split_InsertFields ()V

It fails on GTEX genes (GTEx_Analysis_2016-01-15_v7_RSEMv1.2.22_transcript_tpm.txt.gz - 1.8G large).

Have any of you had a similar problem, and how did you manage to solve it?

Link to stack trace:
https://pastebin.com/at9aGQ9z

Kind regards

**Comment by rileyhgrant** [comment] 2023-04-03 18:40
Closing this issue as it's a functional duplicate of #914

**Closed by rileyhgrant** 2023-04-03 18:40 UTC
