### ISSUE TITLE
Populate new downloads page with v3.1 public file links for Google/Amazon/Azure (when available)

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad-browser#627] opened 2020-10-26 19:02 UTC

**Comment by nawatts** [comment] 2020-10-26 20:30
Duplicate of #621

**Comment by nawatts** [comment] 2020-10-29 14:01
Oops, I see the difference now. The open datasets buckets lag behind the gnomAD buckets.

**Comment by nawatts** [comment] 2020-11-02 21:26
Links for v3.1 data still need to be updated.

**Closed** 2020-11-06 16:00 UTC
